### ISSUE TITLE
Restore old DUNGEONS DAILY QUESTS

### ISSUE THREAD

**Issue by Beltxx** [Blackwhisper-RU/Bug-Tracker#10]
**PHASE 1**
https://www.wowhead.com/npc=20735/archmage-landalock#comments
**(Check comments on wowhead)**
We got after daily 22 gold 22 silver and 2 emblems of heroism.

Utgarde Keep - Ingvar the Plunderer
The Nexus - Keristrasza
Azjol-Nerub - Anub'arak
Ahn'kahet: The Old Kingdom - Herald Volazj
Drak'Tharon Keep - The Prophet Tharon'ja
The Violet Hold - Cyanigosa
Gundrak - Gal'darah
Halls of Stone - Sjonnir The Ironshaper
Utgarde Pinnacle - King Ymiron
The Oculus - Ley-Guardian Eregos
Stratholme Past - Mal'Ganis
Halls of Lightning - Loken

Raid quests must be back on **PHASE 5**

**Comment by Knindzagxg** [comment]
Pull module for Daily Quests.
It's made couple months ago and working without issues.

We can edit Daily rewards easy trough Database.

Link for module bellow:
https://github.com/tkn963/mod-archmage-timear
